all: busqueda_parcial busqueda_parcial_con_espera busca_multiple

busqueda_parcial: busqueda_parcial.c
	gcc -o busqueda_parcial busqueda_parcial.c

busqueda_parcial_con_espera: busqueda_parcial_con_espera.c
	gcc -o busqueda_parcial_con_espera busqueda_parcial_con_espera.c

busca_multiple:
	gcc -o busca_multiple busca_multiple.c

clean:
	rm -f busqueda_parcial busqueda_parcial_con_espera busca_multiple