all: exam1 exam2 exam3 signals

exam1: exam1.c
	gcc -o exam1 exam1.c

exam2: exam2.c
	gcc -o exam2 exam2.c

exam3: exam3.c
	gcc -o exam3 exam3.c

signals: signals.c
	gcc -o signals signals.c

clean:
	rm -f exam1 exam2 exam3