all: aparicions aparicions2 aparicions3

aparicions: aparicions.c
	gcc -o aparicions aparicions.c

aparicions2: aparicions2.c
	gcc -o aparicions2 aparicions2.c

aparicions3: aparicions3.c
	gcc -o aparicions3 aparicions3.c

clean:
	rm -f aparicions aparicions2 aparicions3